
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aspnetcore
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/g/k8s-persistent-volumes/aspnetcore"
  persistentVolumeReclaimPolicy: Retain
  
